[package]

name = "piston_meta"
version = "0.22.2"
authors = ["bvssvni <bvssvni@gmail.com>"]
keywords = ["meta", "language", "encoding", "decoding", "piston"]
description = "A DSL parsing library for human readable text documents"
license = "MIT"
readme = "README.md"
repository = "https://github.com/pistondevelopers/meta.git"
homepage = "https://github.com/pistondevelopers/meta"
documentation = "http://www.piston.rs/meta/piston_meta/index.html"

[dependencies]
read_token = "0.6.0"
range = "0.3.0"

[features]
unstable = []
