[package]

name = "piston_meta"
version = "0.1.0"
authors = ["bvssvni <bvssvni@gmail.com>"]
keywords = ["meta", "language", "encoding", "decoding", "piston"]
description = "Meta parsing and encoding for data oriented design"
license = "MIT"
readme = "README.md"
repository = "https://github.com/pistondevelopers/meta.git"
homepage = "https://github.com/pistondevelopers/meta"

[dependencies]
read_token = "0.1.0"
range = "0.1.0"
