[package]

name = "piston_meta"
version = "0.1.9"
authors = ["bvssvni <bvssvni@gmail.com>"]
keywords = ["meta", "language", "encoding", "decoding", "piston"]
description = "A research project of meta parsing and composing for data"
license = "MIT"
readme = "README.md"
repository = "https://github.com/pistondevelopers/meta.git"
homepage = "https://github.com/pistondevelopers/meta"

[dependencies]
read_token = "0.1.1"
range = "0.1.1"
