[package]

name = "piston_meta"
version = "0.12.0"
authors = ["bvssvni <bvssvni@gmail.com>"]
keywords = ["meta", "language", "encoding", "decoding", "piston"]
description = "A DSL parsing library for human readable text documents"
license = "MIT"
readme = "README.md"
repository = "https://github.com/pistondevelopers/meta.git"
homepage = "https://github.com/pistondevelopers/meta"

[dependencies]
read_token = "0.2.2"
range = "0.1.1"

[features]
unstable = []
